<?php
/** @noinspection PhpIncompatibleReturnTypeInspection
 * @noinspection ReturnTypeCanBeDeclaredInspection
 * @noinspection DuplicatedCode
 * @noinspection PhpUnused
 * @noinspection PhpUndefinedMethodInspection
 * @noinspection PhpUnusedLocalVariableInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection NullPointerExceptionInspection
 * @noinspection SenselessProxyMethodInspection
 * @noinspection PhpParameterByRefIsNotUsedAsReferenceInspection
 */
namespace example\model;
use eftec\PdoOne;
use Exception;

/**
 * Generated by PdoOne Version 2.2.5 Date generated Sun, 06 Sep 2020 17:11:20 -0400. 
 * DO NOT EDIT THIS CODE. THIS CODE WILL SELF GENERATE.
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class Invoice
 * <pre>
 * $code=$pdoOne->generateAbstractModelClass({args});
 * </pre>
 */
abstract class AbstractInvoice
{
	/** @var int $IdInvoice  */
	public $IdInvoice;
	/** @var datetime $Date  */
	public $Date;
	/** @var int $IdCustomer  */
	public $IdCustomer;

	/** @var Customer $_IdCustomer manytoone */
    public $_IdCustomer;
	/** @var InvoiceDetail[] $_invoice_details onetomany */
    public $_invoice_details;


    /**
     * AbstractInvoice constructor.
     *
     * @param array|null $array
     */
    public function __construct($array=null)
    {
        if($array===null) {
            return;
        }
        foreach($array as $k=>$v) {
            $this->{$k}=$v;
        }
    }

    //<editor-fold desc="array conversion">
    public static function fromArray($array) {
        if($array===null) {
            return null;
        }
        $obj=new Invoice();
		$obj->IdInvoice=isset($array['IdInvoice']) ?  $array['IdInvoice'] : null;
		$obj->Date=isset($array['Date']) ?  $array['Date'] : null;
		$obj->IdCustomer=isset($array['IdCustomer']) ?  $array['IdCustomer'] : null;
		$obj->_IdCustomer=isset($array['_IdCustomer']) ? 
            $obj->_IdCustomer=Customer::fromArray($array['_IdCustomer']) 
            : null; // manytoone
		($obj->_IdCustomer !== null) 
            and $obj->_IdCustomer->IdCustomer=&$obj->IdCustomer; // linked manytoone
		$obj->_invoice_details=isset($array['_invoice_details']) ?  
            $obj->_invoice_details=InvoiceDetail::fromArrayMultiple($array['_invoice_details']) 
            : null; // onetomany

        return $obj;
    }
    
    /**
     * It converts the current object in an array
     * 
     * @return mixed
     */
    public function toArray() {
        return static::objectToArray($this);
    }
    
    /**
     * It converts an array of arrays into an array of objects.
     * 
     * @param array|null $array
     *
     * @return array|null
     */
    public static function fromArrayMultiple($array) {
        if($array===null) {
            return null;
        }
        $objs=[];
        foreach($array as $v) {
            $objs[]=self::fromArray($v);
        }
        return $objs;
    }
    //</editor-fold>
    
} // end class