<?php
/** @noinspection PhpIncompatibleReturnTypeInspection
 * @noinspection ReturnTypeCanBeDeclaredInspection
 * @noinspection DuplicatedCode
 * @noinspection PhpUnused
 * @noinspection PhpUndefinedMethodInspection
 * @noinspection PhpUnusedLocalVariableInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection NullPointerExceptionInspection
 * @noinspection SenselessProxyMethodInspection
 * @noinspection PhpParameterByRefIsNotUsedAsReferenceInspection
 */
namespace example\model;
use eftec\PdoOne;
use Exception;

/**
 * Generated by PdoOne Version 2.2.5 Date generated Sun, 06 Sep 2020 09:40:12 -0400. 
 * YOU COULD EDIT THIS CODE
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class Invoice
 * <pre>
 * $code=$pdoOne->generateCodeClass({args});
 * </pre>
 */
class Invoice extends AbstractInvoice
{

    
} // end class