<?php
/** @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
namespace example\repo;
use example\model\Invoice;
use Exception;

/**
 * Generated by PdoOne Version 2.2.5 Date generated Sun, 06 Sep 2020 16:29:57 -0400. 
 * EDIT THIS CODE.
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class InvoiceRepo
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''invoices'',''example\repo'','array('customers'=>'CustomerRepo','invoice_details'=>'InvoiceDetailRepo','invoices'=>'InvoiceRepo',)',''example\model\Invoice'');
 * </pre>
 */
class InvoiceRepo extends AbstractInvoiceRepo
{
    const ME=__CLASS__; 
    const MODEL= Invoice::class;
  
    
}